config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'ui_kit', to: 'pages#ui_kit'
  root to: "pages#home"
  resources :listings do
    resources :bookings, except: [:index, :show, :edit, :update, :destroy]
  end

  resources :bookings, only: [:index, :show, :edit, :update, :destroy] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  has_one :review, dependent: :destroy
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bookings
  geocoded_by :location
  after_validation :geocode if :will_save_change_to_location?
  has_many :reviews, through: :bookings
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :content, :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :listings, dependent: :destroy
  has_many :bookings
  has_many :reviews, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[update show edit destroy]

  def index
    @bookings = Booking.where(user: current_user)
  end

  def show
    @review = Review.new
  end

  def new
    @booking = Booking.new
    @listing = Listing.find(params[:listing_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.listing = Listing.find(params[:listing_id])
    if @booking.save
      redirect_to bookings_path
    end
  end

  def edit

  end

  def update
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[update show edit destroy]

  def index
    @listings = Listing.all
    @markers = @listings.geocoded.map do |listing|
      {
        lat: listing.latitude,
        lng: listing.longitude
      }
    end
    if params[:query].present?
      sql_query = <<~SQL
        listings.location ILIKE :query
      SQL
      @listings = Listing.where(sql_query, query: "%#{params[:query]}%")
    else
      @listings = Listing.all
    end
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    redirect_to listings_path if @listing.save
  end

  def update
    redirect_to listing_path(@listing) if @listing.update(listing_params)
  end

  def destroy
    @listing.destroy
    redirect_to listings_path, status: :see_other
  end

  def show
    @reviews = @listing.reviews
    @booking = Booking.new
  end

  def edit
  end

  private

  def listing_params
    params.require(:listing).permit(:title, :location, :content, :price, :image)
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @listings = Listing.all
  end

  def ui_kit
    @listing = Listing.first
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @booking = Booking.find(params[:booking_id])
    @review = @booking.build_review(review_params)

    if @review.save
      redirect_to @booking.listing, notice: 'Review was successfully created.'
    else
      render "bookings/show", status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<div class='booking-container'>
  <div class='container pt-2'>
    <h1 class='new-booking-header'>Create a New Booking</h1>
    <div class='col'>
      <%= simple_form_for [@listing, @booking] do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <div class='btns-container'>
          <%= f.button :submit, :id => 'btn-submit'  %>
          <%= link_to "Cancel", :back, :id => 'btn-cancel'  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<h1>Edit Booking</h1>
<%= simple_form_for [@listing, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.button :submit %>
<% end %>
<%= link_to "Cancel", :back %>

app/views/bookings/index.html.erb
  <div class='container pt-5 mt-4 mb-4'>
    <div class='row'>
    <h3>Booking Confirmation</h3>
      <% @bookings.each do |booking| %>
        <div class='col-md-3 mb-4'>
          <%= link_to booking_path(booking), class: "no-decoration" do %>
            <%= render "shared/booking", booking: booking %>
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <p><%= link_to "Back to listings", root_path, class: "no-decoration" %></p>
  </div>
</div>




<!-- 1. Replace "My Bookings" with "Booking confirmation" -->
<!-- 2. Show how much the listing is going to cost for the booking period (price X (start date - end date)) -->
<!-- 3. Show a discount section and apply discount if (first time booking == true OR booking period > 20 days)-->

app/views/bookings/show.html.erb
<div class="container pt-5 mt-4 mb-4">
  <div class="row">
<h2><%= @booking.listing.title %></h2>
<h4><%= @booking.listing.location %></h4>
<img class="img" src="<%= @booking.listing.image %>" alt="" width="300" height="300">
<p></p>
<p>Check In Date: <%= @booking.start_date %> - Check Out Date: <%= @booking.end_date %></p>

</div>


<h3>New review</h3>
<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, input_html: { min: '0', max: '5', :style=> 'width: 50%' } %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
<p></p>
<div class ="row">
 <div class='col-md-3 mb-4'>
 <p><%= link_to 'Edit Booking', edit_booking_path(@booking) %></p>
 </div>
  <div class='col-md-3 mb-4'>
   <p><%= link_to 'Delete Booking', booking_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
 </div>
  <div class='col-md-3 mb-4'>
   <p><%= link_to "Cancel", :back %></p>
 </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirBNBClone</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href='https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css' rel='stylesheet' />
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body class='pt-3'>
  <%= render 'shared/navbar' %>
    <%= yield %>
  <div class='dummy--spacer'></div>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/delete.html.erb
<h1>Listings#delete</h1>
<p>Find me in app/views/listings/delete.html.erb</p>

app/views/listings/edit.html.erb
<h1>Edit <%= @listing.title  %></h1>
<%= simple_form_for @listing do |f| %>
  <%= f.input :title %>
  <%= f.input :location %>
  <%= f.input :content %>
  <%= f.input :price %>
  <%= f.input :image %>
  <%= f.button :submit %>
<% end %>

<%= link_to "Cancel", listing_path(@listing) %>

app/views/listings/index.html.erb
<div class='container pt-5 mt-4'>
<div class='row pt-2 pb-2'>
<h3>These are our apartments in this location</h3>
</div>
  <div class='row'>
    <div class="col-lg-6">
      <div class='row'>
        <% @listings.in_groups_of(2, false) do |group| %>
          <div class='col-lg-6'>
            <% group.compact.each do |listing| %>
              <div class="mb-3">
                <%= link_to listing_path(listing), class: "cards col-6 col-md-4 col-lg-3 no-decoration" do %>
                  <%= render "shared/card", listing: listing %>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="sticky-top">
        <div class="map">
          <div class="map" style="height: 100vh"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<div class='container pt-5'>
  <h1 class='new-booking-header'>Create a New Listing</h1>
  <div class='col-6'>
    <%= simple_form_for @listing do |f| %>
      <%= f.input :title %>
      <%= f.input :location %>
      <%= f.input :content %>
      <%= f.input :price %>
      <%= f.input :image %>
      <div class='btns-container'>
        <%= f.button :submit, :id => 'btn-submit' %>
        <%= link_to "Cancel", listings_path, :id => 'btn-cancel' %>
      </div>
    <% end %>
  </div>
</div>

app/views/listings/show.html.erb
<div class="container pt-5">
  <div class="row">
    <h2><strong>Details of <%= @listing.title %></strong></h2>
      <div class="d-flex justify-content-between">
        <p> <%= @listing.location %></p>
        <p>Save <i class="fa-regular fa-heart"></i> Share <i class="fa-sharp fa-solid fa-arrow-up-from-bracket"></i></p>
      </div>
      <div class="d-flex justify-content-between">
        <% if @reviews.present? %>
          <p> <%= @reviews.first.rating %> <i class="fa-solid fa-star"></i>  Reviews: <%=@reviews.count %></p>
          <% end %>
      </div>
  </div>


  <div class= grid-image>
    <%= render "shared/grid", listing: @listing %>
  </div>

  <div class="info-details">
    <h3>This Property is Hosted by: Robertae F </h3>
    <p> <i class="fa-solid fa-children"></i> 4 guests  | <i class="fa-solid fa-people-roof"></i> 2 bedrooms | <i class="fa-solid fa-bed"></i> 4 beds | <i class="fa-solid fa-bath"></i> 2 baths</p>
    <p><%= @listing.content %></p>
    <p><strong>€<%= @listing.price %></strong></p>
  </div>

  <div class="d-flex justify-content-between">
    <div class="arrival">
    <p><i class="fa-solid fa-door-closed"></i> <strong>Self check-in</strong><br>
      You can check in with the doorman.</p>
    <p><i class="fa-solid fa-car"></i> <strong>Drive Right Up</strong><br>
      You can park your vechile in the private driveway</p>
    <p><i class="fa-regular fa-star"></i> <strong>Experienced host</strong><br>
      Novasol has 240 reviews for other places.</p><br>
    <p>- Free parking on site<br>
      - Indoor swimming pool<br>
      - Not suitable for youth groups<br>
      - Optional: Bedlinen incl towels<br><br>
        No pets allowed
    <div class="offers">
      <br>
      <h3>What this accommation has to  offer:</h3>
      <p><i class="fa-solid fa-kitchen-set"></i>-Kitchen</p>
      <p><i class="fa-solid fa-wifi"></i>-Wifi</p>
      <p><i class="fa-solid fa-desktop"></i>-Dedicated workspace </p>
      <p><i class="fa-solid fa-water-ladder"></i>-Pool</p>
      <p><i class="fa-solid fa-shirt"></i>-Washer/Dryer</p>
      <p><i class="fa-solid fa-tv"></i>-TV</p>
    </div>
    </p>
  </div>

  <div class="booking-container">
    <%= render "bookings/new", listing: @listing %><br>
    <div class="buttons-container ">
      <p><%= link_to "Delete", listing_path(@listing),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger" %></p>
      <p><%= link_to "Edit Listing", edit_listing_path(@listing),class: "no-decoration" %></p>
      <p><%= link_to "Back to Listings", listings_path ,class: "no-decoration"%></p>
    </div>
  </div>


</div>
<div>
<br>
  <h3>Reviews</h3>
    <% @listing.reviews.each do |review| %>
     <p>
      <%= review.content %>
      <%= review.rating  %> <i class="fa-solid fa-star"></i>
      </p>
    <% end %>
</div>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>

app/views/pages/home.html.erb
<%= render "shared/hero" %>

<h2 class='home--subheading'>Current Listings on Offer</h2>

</div>
  <div class='container'>
    <div class='row'>
      <% @listings.each do |listing| %>
        <div class='col-md-3 mb-4'>
          <%= link_to listing_path(listing), class: "no-decoration" do %>
            <%= render "shared/card", listing: listing %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/ui_kit.html.erb
<h1>Test Page</h1>



<%# <%= render "shared/card", danko: "1" %>

<%# booking button %>

<%# listing card %>

<%# cards grid %>
<%= render "shared/grid", listing: @listing  %>
<%# <%= render "shared/card", listing: @listing %>

<%# <%= render "shared/footer" %>

app/views/shared/_avatar.sm.html.erb
<img class="avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/cveneziani" />

app/views/shared/_avatar_lg.html.erb
<img class="avatar-large" alt="avatar-large" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>

app/views/shared/_booking.html.erb
<%= link_to booking_path(booking), class: "no-decoration" do %>
  <div>
    <div class="card-trip">
      <div class = "card-image">
        <img src="<%= booking.listing.image %>" style="width: 250px; height: 250px" />
      </div>
      <div class = "card-heart">
        <i class="fa-regular fa-heart"></i>
      </div>
      <div class="card-trip-infos">
          <p><strong><%= booking.listing.title %>, <% booking.listing.location %></strong></p>
          <p><%= booking.listing.content %></p>
            <p>Check In: <%= booking.start_date %></p>
            <p>Check Out: <%= booking.end_date %></p>
            <p>Duration of stay: (<%= (booking.end_date - booking.start_date).to_i%> days)</p>
      </div>
      <div class="card-trip-pricing">
        <h3>Total €<%= booking.listing.price * ( booking.end_date - booking.start_date) %></h3>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_bookingConfirmation.html.erb
<%= link_to booking_path(booking), class: "no-decoration" do %>
<div class="m-3 p-4 text-center bg-dark rounded-4">
  <h1>Booking successful!</h1>
  <h3>Your stay in <%= booking.listing.title %>, <%= booking.listing.location %></h3>
  <h3>From <strong><%= booking.start_date %></strong> to <strong><%= booking.end_date %></strong></h3>

  <p style="color: white;">Price per night: €<%= booking.listing.price %></p>
  <p style="color: white;">Total: €<%= booking.listing.price * (booking.end_date - booking.start_date) %></p>
</div>

<div class="text-center mb-5">
  <h1><%= link_to bookings_path, class: "btn btn-primary btn-flat rounded-5" do %>
    <i class="fa-solid fa-calendar-days"></i>  Manage My Bookings
  <% end %></h1>
</div>

app/views/shared/_button.html.erb
<a class="btn btn-flat" href="#">Book now</a>

app/views/shared/_card.html.erb
<div class="">
  <div class="card-trip">
    <div class = "card-image">
      <img src="<%= listing.image %>" style="width: 250px; height: 250px" />
    </div>
    <div class = "card-heart">
      <i class="fa-regular fa-heart"></i>
    </div>
    <div class='card--bottom--section'>
      <div class="card-trip-infos">
          <h3 class="card--title"><%= listing.title %></h3>
          <p><%= listing.content %></p>
      </div>
      <div class="card-trip-pricing">
        <h3>€<%= listing.price %></h3>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This clone is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_grid.html.erb
<div class="container">
  <div class="row">
      <div class="col-6 p-1" style="height: 400px">
        <div class="h-100 round-image" style="background-image: url(<%= image_path(@listing.image) %>); background-repeat: no-repeat; background-size: cover;"></div>
      </div>

    <div class="row col-6">

      <div class="col-6 p-1">
        <div class="h-100 round-image" style="background-image: url(https://source.unsplash.com/random/250x250/?kitchen); background-repeat: no-repeat; background-size: cover;"></div>
      </div>

      <div class="col-6 p-1">
        <div class="h-100 round-image" style="background-image: url(https://source.unsplash.com/random/250x250/?bedroom); background-repeat: no-repeat; background-size: cover;"></div>
      </div>

      <div class="col-6 p-1">
        <div class="h-100 round-image" style="background-image: url(https://source.unsplash.com/random/250x250/?bathroom); background-repeat: no-repeat; background-size: cover;"></div>
      </div>


      <div class="col-6 p-1">
        <div class="h-100 round-image" style="background-image: url(https://source.unsplash.com/random/250x250/?balcony); background-repeat: no-repeat; background-size: cover;"></div>
      </div>


    </div>
  </div>
</div>

app/views/shared/_hero.html.erb
  <div  class='hero row'>
    <h1 class='col col-6 hero--title'>Find the perfect place for your travels.</h1>
    <div class='col col-4'>
      <div class="input-group">
        <%= form_with url: listings_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                      params[:query],
                      class: "form-control",
                      placeholder: "Find a City" %>
          <%= submit_tag "Search", id: 'btn-submit' %>
        <% end %>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top" style="padding-top: 0.5rem; padding-bottom: 0.5rem;">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag('vacaypurple.png', class: "w-95") %>
    <% end %>
<marquee behavior="scroll" direction="right" style="color: purple; font-size: 20">Vacay Away</marquee>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto" style="padding-top: 0.5rem;">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Listing", new_listing_path, class: "nav-link" %>
          </li>
           <ul class="navbar-nav mr-auto">

    </ul>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},
                  class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_notification.html.erb
<div class="notification">
  <img src='https://kitt.lewagon.com/placeholder/users/arthur-littm' class="avatar-large" />
  <div class="notification-content">
    <p><small>14th January</small></p>
    <p>Lorem ipsum dolor sit amet, <strong>consectetur</strong> adipisicing elit.</p>
  </div>

  <div class="notification-actions">
    <a href="#">Edit <i class="fas fa-pencil-alt"></i></a>
    <a href="#">Delete <i class="far fa-trash-alt"></i></a>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get">
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
</form>

app/views/shared/_tabs.html.erb
<ul class="list-inline tabs-underlined">
  <li>
    <a href="#" class="tab-underlined active">Bookings</a>
  </li>
  <li>
    <a href="#" class="tab-underlined">Requests</a>
  </li>
  <li>
    <a href="#" class="tab-underlined">Conversations</a>
  </li>
</ul>